name: riverpod_standard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.4.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.17
  state_notifier: ^0.7.2+1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0
  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


